// <auto-generated />
using System;
using App.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Domain.Auth.EmailVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<bool>("Used")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("used");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_email_verifications_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_email_verifications_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_email_verifications_user_id");

                    b.ToTable("email_verifications", null, t =>
                        {
                            t.HasCheckConstraint("ck_email_verifications_expiry_future", "\"expires_at_utc\" > NOW() - INTERVAL '7 days'");
                        });
                });

            modelBuilder.Entity("App.Domain.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id");

                    b.ToTable("clients", null, t =>
                        {
                            t.HasCheckConstraint("ck_clients_company_or_person", " (btrim(coalesce(company_name, '')) <> '')  OR (btrim(coalesce(first_name,  '')) <> '')  OR (btrim(coalesce(last_name,   '')) <> '') ");
                        });
                });

            modelBuilder.Entity("App.Domain.Common.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at_utc");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("ix_outbox_messages_processed_at_utc");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("App.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyEmail")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("company_email");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<int?>("Department")
                        .HasColumnType("integer")
                        .HasColumnName("department");

                    b.Property<string>("EmploymentType")
                        .HasColumnType("text")
                        .HasColumnName("employee_type");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("end_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<DateTimeOffset?>("HireDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("hire_date");

                    b.Property<bool>("IsPreapproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_preapproved");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("PreferredName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("preferred_name");

                    b.Property<Guid?>("RecommendedRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommended_role_id");

                    b.Property<string>("SalaryType")
                        .HasColumnType("text")
                        .HasColumnName("salary_type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WorkLocation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("work_location");

                    b.HasKey("Id");

                    b.HasIndex("CompanyEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_employees_company_email")
                        .HasFilter("company_email IS NOT NULL AND deleted_at_utc IS NULL");

                    b.HasIndex("RecommendedRoleId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_employees_user_id")
                        .HasFilter("user_id IS NOT NULL AND deleted_at_utc IS NULL");

                    b.HasIndex("LastName", "FirstName")
                        .HasDatabaseName("ix_employees_last_first")
                        .HasFilter("deleted_at_utc IS NULL");

                    b.ToTable("employees", null, t =>
                        {
                            t.HasCheckConstraint("ck_employee_preapproved_requires_email", "\"is_preapproved\" = FALSE OR \"company_email\" IS NOT NULL");

                            t.HasCheckConstraint("ck_employees_dates_order", "end_date IS NULL OR hire_date IS NULL OR hire_date <= end_date");

                            t.HasCheckConstraint("ck_employees_employment_type_valid", "employee_type IS NULL OR employee_type IN ('FullTime','PartTime')");

                            t.HasCheckConstraint("ck_employees_first_not_empty", "length(trim(first_name)) > 0");

                            t.HasCheckConstraint("ck_employees_last_not_empty", "length(trim(last_name))  > 0");

                            t.HasCheckConstraint("ck_employees_salary_type_valid", "salary_type IS NULL OR salary_type IN ('Salary','Hourly')");
                        });
                });

            modelBuilder.Entity("App.Domain.Employees.EmployeePosition", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.HasKey("EmployeeId", "PositionId");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_employee_positions_employee_id");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_employee_positions_position_id");

                    b.ToTable("employee_positions", (string)null);
                });

            modelBuilder.Entity("App.Domain.Employees.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresLicense")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_license");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_positions_code_active")
                        .HasFilter("\"deleted_at_utc\" IS NULL");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_positions_name_active")
                        .HasFilter("\"deleted_at_utc\" IS NULL");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("App.Domain.Users.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("App.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email")
                        .HasFilter("deleted_at_utc IS NULL");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("App.Domain.Clients.Client", b =>
                {
                    b.OwnsOne("App.Domain.Common.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ClientId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Line1")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("Address_Line_1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("Address_Line_2");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)");

                            b1.Property<string>("State")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("ClientId");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("App.Domain.Employees.Employee", b =>
                {
                    b.HasOne("App.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RecommendedRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("App.Domain.Users.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("App.Domain.Employees.Employee", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("App.Domain.Common.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Line1")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("Address_Line_1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("Address_Line_2");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)");

                            b1.Property<string>("State")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Domain.Employees.EmployeePosition", b =>
                {
                    b.HasOne("App.Domain.Employees.Employee", "Employee")
                        .WithMany("Positions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("App.Domain.Employees.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("App.Domain.Users.User", b =>
                {
                    b.HasOne("App.Domain.Users.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("App.Domain.Employees.Employee", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("App.Domain.Users.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("App.Domain.Users.User", b =>
                {
                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
