using App.Domain.Contacts;

namespace App.Infrastructure.Persistence.Seed.Factories;

internal static class ContactSeedFactory
{
    public static IEnumerable<Contact> All =>
    [
        Contact.Seed(clientId: null, title: null, firstName: "Jonathan", middleName: null, lastName: "Nieman",
            suffix: "PE", company: "Advanced Wall Engineering", department: null, jobTitle: null,
            businessStreet1: null, businessStreet2: null, businessStreet3: null, businessCity: null,
            businessState: null, businessPostalCode: null, businessCountry: null, businessPhone: "(615) 397-5705",
            mobilePhone: null, primaryPhone: null, emailAddress: "engineering@advwallengineering.com",
            webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Glenn", middleName: "D.", lastName: "Shane",
            suffix: null, company: "AT&T", department: null, jobTitle: "MGR OSP PLNG & ENGRG DESIGN",
            businessStreet1: null, businessStreet2: null, businessStreet3: null, businessCity: null,
            businessState: null, businessPostalCode: null, businessCountry: null, businessPhone: "(270) 831-3025",
            mobilePhone: "(270) 993-8074", primaryPhone: null, emailAddress: "GLENN.SHANE@ATT.COM", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Silas", middleName: null, lastName: "Bohlen",
            suffix: null, company: "Atmos Energy", department: null, jobTitle: "Sr. Engineer",
            businessStreet1: "3275 Highland Pointe Drive", businessStreet2: null, businessStreet3: null,
            businessCity: "Owensboro", businessState: "KY", businessPostalCode: "42303",
            businessCountry: "United States of America", businessPhone: "(270) 685-8020",
            mobilePhone: "(270) 570-0445", primaryPhone: null, emailAddress: "Silas.Bohlen@atmosenergy.com",
            webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Ben", middleName: null, lastName: "Grove",
            suffix: null, company: "Axiom Architecture, PLLC", department: null, jobTitle: "Architect",
            businessStreet1: "2625 Frederica Street", businessStreet2: null, businessStreet3: null,
            businessCity: "Owensboro", businessState: "KY", businessPostalCode: "42301", businessCountry: null,
            businessPhone: null, mobilePhone: "(270) 860-1515", primaryPhone: null,
            emailAddress: "ben@axiom-architecture.com", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Jennifer", middleName: null, lastName: "Rudd",
            suffix: null, company: "Axiom Architecture, PLLC", department: null, jobTitle: "Architectural Designer",
            businessStreet1: "2625 Frederica Street", businessStreet2: null, businessStreet3: null,
            businessCity: "Owensboro", businessState: "KY", businessPostalCode: "42301", businessCountry: null,
            businessPhone: null, mobilePhone: "(270) 313-5305", primaryPhone: null,
            emailAddress: "jennifer@axiom-architecture.com", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Neal", middleName: null, lastName: "Wedding",
            suffix: null, company: "BGMU", department: null, jobTitle: "Engineer", businessStreet1: "801 Center St",
            businessStreet2: null, businessStreet3: null, businessCity: "Bowling Green", businessState: "KY",
            businessPostalCode: "42101", businessCountry: null, businessPhone: "(270) 782-3568", mobilePhone: null,
            primaryPhone: null, emailAddress: "neal.wedding@bgmu.com", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Kevin", middleName: null, lastName: "Collignon",
            suffix: null, company: "Bluegrass Engineering", department: null, jobTitle: "Engineer",
            businessStreet1: "1722 Moylan Lane", businessStreet2: null, businessStreet3: null,
            businessCity: "Bowling Green", businessState: "KY", businessPostalCode: "42104", businessCountry: null,
            businessPhone: "(310) 770-5572", mobilePhone: null, primaryPhone: null,
            emailAddress: "kbce57@yahoo.com", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Mike", middleName: null, lastName: "Hamilton",
            suffix: null, company: "Breckinridge County Fiscal Court", department: null, jobTitle: null,
            businessStreet1: "208 South Main Street", businessStreet2: null, businessStreet3: null,
            businessCity: "Hardinsburg", businessState: "KY", businessPostalCode: "40143", businessCountry: null,
            businessPhone: "(270) 756-2269", mobilePhone: null, primaryPhone: null,
            emailAddress: "mike.hamilton@breckinridgecounty.ky.gov", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Kasey", middleName: null, lastName: "Emmick",
            suffix: null, company: "Bryant Construction", department: null, jobTitle: null,
            businessStreet1: "1009 Booth Ave", businessStreet2: null, businessStreet3: null,
            businessCity: "Owensboro", businessState: "KY", businessPostalCode: "42301", businessCountry: null,
            businessPhone: "(270) 683-1155", mobilePhone: null, primaryPhone: null,
            emailAddress: "Kasey@bryantconstructionky.com", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Matt", middleName: null, lastName: "Hayden",
            suffix: null, company: "Bryant Engineering, Inc", department: null, jobTitle: null,
            businessStreet1: "1705 Starlite Dr", businessStreet2: null, businessStreet3: null,
            businessCity: "Owensboro", businessState: "KY", businessPostalCode: "42301", businessCountry: null,
            businessPhone: "(270) 683-1155", mobilePhone: null, primaryPhone: null,
            emailAddress: "mhayden@bryant-eng.com", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Kevin", middleName: null, lastName: "Grant",
            suffix: null, company: "Bryant Engineering, Inc", department: null, jobTitle: null,
            businessStreet1: "1705 Starlite Dr", businessStreet2: null, businessStreet3: null,
            businessCity: "Owensboro", businessState: "KY", businessPostalCode: "42301", businessCountry: null,
            businessPhone: "(270) 683-1155", mobilePhone: null, primaryPhone: null,
            emailAddress: "kgrant@bryant-eng.com", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Chris", middleName: "D.", lastName: "Law",
            suffix: null, company: "Bryant Engineering, Inc", department: null, jobTitle: null,
            businessStreet1: "1705 Starlite Dr", businessStreet2: null, businessStreet3: null,
            businessCity: "Owensboro", businessState: "KY", businessPostalCode: "42301", businessCountry: null,
            businessPhone: "(270) 683-1155", mobilePhone: null, primaryPhone: null,
            emailAddress: "claw@bryant-eng.com", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Joe", middleName: null, lastName: "Watson",
            suffix: null, company: "Bryant Engineering, Inc", department: null, jobTitle: null,
            businessStreet1: "1705 Starlite Dr", businessStreet2: null, businessStreet3: null,
            businessCity: "Owensboro", businessState: "KY", businessPostalCode: "42301", businessCountry: null,
            businessPhone: "(270) 683-1155", mobilePhone: null, primaryPhone: null,
            emailAddress: "jwatson@bryant-eng.com", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Steve", middleName: null, lastName: "Hayden",
            suffix: null, company: "Bryant Engineering, Inc", department: null, jobTitle: null,
            businessStreet1: "1705 Starlite Dr", businessStreet2: null, businessStreet3: null,
            businessCity: "Owensboro", businessState: "KY", businessPostalCode: "42301", businessCountry: null,
            businessPhone: "(270) 683-1155", mobilePhone: null, primaryPhone: null,
            emailAddress: "shayden@bryant-eng.com", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Cody", middleName: null, lastName: "Henderson",
            suffix: null, company: "City of Bowling Green", department: null, jobTitle: null,
            businessStreet1: "1017 West Main Street", businessStreet2: null, businessStreet3: null,
            businessCity: "Bowling Green", businessState: "KY", businessPostalCode: "42101", businessCountry: null,
            businessPhone: "(270) 393-3000", mobilePhone: null, primaryPhone: null,
            emailAddress: "cody.henderson@bgky.org", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Keith", middleName: null, lastName: "Payne",
            suffix: null, company: "City of Hartford", department: null, jobTitle: null,
            businessStreet1: "123 East Washington St", businessStreet2: null, businessStreet3: null,
            businessCity: "Hartford", businessState: "KY", businessPostalCode: "42347", businessCountry: null,
            businessPhone: "(270) 298-3612", mobilePhone: null, primaryPhone: null,
            emailAddress: "cityofhartford@gmail.com", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Manuel", middleName: null, lastName: "Ball",
            suffix: null, company: "Comcast Cable", department: null, jobTitle: "Construction Coordinator",
            businessStreet1: "4209 US Highway 41 N", businessStreet2: null, businessStreet3: null,
            businessCity: "Henderson", businessState: "KY", businessPostalCode: "42420",
            businessCountry: "United States", businessPhone: "(812) 453-2484", mobilePhone: null,
            primaryPhone: null, emailAddress: "MANUEL_BALL@comcast.com", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Bill", middleName: null, lastName: "Jagoe",
            suffix: null, company: "Jagoe Homes", department: null, jobTitle: null,
            businessStreet1: "1115 Tamarack Rd", businessStreet2: null, businessStreet3: null,
            businessCity: "Owensboro", businessState: "KY", businessPostalCode: "42301", businessCountry: null,
            businessPhone: "(270) 683-6156", mobilePhone: null, primaryPhone: null, emailAddress: null,
            webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Jim", middleName: null, lastName: "Adams",
            suffix: null, company: "Jagoe Homes", department: null, jobTitle: null,
            businessStreet1: "1115 Tamarack Rd", businessStreet2: null, businessStreet3: null,
            businessCity: "Owensboro", businessState: "KY", businessPostalCode: "42301", businessCountry: null,
            businessPhone: "(270) 683-6156", mobilePhone: null, primaryPhone: null,
            emailAddress: "jadams@jagoehomes.com", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Steffan", middleName: null, lastName: "Hart",
            suffix: null, company: "KRWA", department: null, jobTitle: "Circuit Rider II",
            businessStreet1: "1151 Harry Sykes Way", businessStreet2: null, businessStreet3: null,
            businessCity: "Lexington", businessState: "KY", businessPostalCode: "40504", businessCountry: null,
            businessPhone: "(859) 608-8335", mobilePhone: null, primaryPhone: null, emailAddress: "shart@krwa.org",
            webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Scott", middleName: null, lastName: "Atherton",
            suffix: null, company: "KYTC District 2", department: null, jobTitle: "Branch Manager",
            businessStreet1: "1840 N Main St", businessStreet2: null, businessStreet3: null,
            businessCity: "Madisonville", businessState: "KY", businessPostalCode: "42431", businessCountry: null,
            businessPhone: "(270) 824-7080", mobilePhone: null, primaryPhone: null,
            emailAddress: "scott.atherton@ky.gov", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Taylor", middleName: null, lastName: "Franklin",
            suffix: null, company: "KYTC District 2", department: null, jobTitle: "Branch Manager",
            businessStreet1: "1840 N Main St", businessStreet2: null, businessStreet3: null,
            businessCity: "Madisonville", businessState: "KY", businessPostalCode: "42431", businessCountry: null,
            businessPhone: "(270) 824-7080", mobilePhone: null, primaryPhone: null,
            emailAddress: "taylor.franklin@ky.gov", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Sarah", middleName: null, lastName: "Payton",
            suffix: null, company: "KYTC District 2", department: null, jobTitle: null,
            businessStreet1: "1840 N Main St", businessStreet2: null, businessStreet3: null,
            businessCity: "Madisonville", businessState: "KY", businessPostalCode: "42431", businessCountry: null,
            businessPhone: "(270) 824-7080", mobilePhone: null, primaryPhone: null,
            emailAddress: "sarah.payton@ky.gov", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Terry", middleName: null, lastName: "Humphries",
            suffix: null, company: "KYTC District 3", department: null, jobTitle: "Branch Manager",
            businessStreet1: "900 Morgantown Road", businessStreet2: null, businessStreet3: null,
            businessCity: "Bowling Green", businessState: "KY", businessPostalCode: "42101", businessCountry: null,
            businessPhone: "(270) 746-7898", mobilePhone: null, primaryPhone: null,
            emailAddress: "terry.humphries@ky.gov", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Tony", middleName: null, lastName: "Kelly",
            suffix: null, company: "KYTC District 3", department: null, jobTitle: null,
            businessStreet1: "900 Morgantown Road", businessStreet2: null, businessStreet3: null,
            businessCity: "Bowling Green", businessState: "KY", businessPostalCode: "42101", businessCountry: null,
            businessPhone: "(270) 746-7898", mobilePhone: null, primaryPhone: null,
            emailAddress: "tony.kelly@ky.gov", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "David", middleName: null, lastName: "Mulloy",
            suffix: null, company: "KYTC District 3", department: null, jobTitle: null,
            businessStreet1: "900 Morgantown Road", businessStreet2: null, businessStreet3: null,
            businessCity: "Bowling Green", businessState: "KY", businessPostalCode: "42101", businessCountry: null,
            businessPhone: "(270) 746-7898", mobilePhone: null, primaryPhone: null,
            emailAddress: "david.mulloy@ky.gov", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Jamie", middleName: null, lastName: "Murphy",
            suffix: null, company: "KYTC District 3", department: null, jobTitle: "Section Supervisor",
            businessStreet1: "900 Morgantown Road", businessStreet2: null, businessStreet3: null,
            businessCity: "Bowling Green", businessState: "KY", businessPostalCode: "42101", businessCountry: null,
            businessPhone: "(270) 746-7898", mobilePhone: null, primaryPhone: null,
            emailAddress: "jamie.murphy@ky.gov", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Walt", middleName: null, lastName: "Beasley",
            suffix: null, company: "KYTC District 3", department: null, jobTitle: null,
            businessStreet1: "900 Morgantown Road", businessStreet2: null, businessStreet3: null,
            businessCity: "Bowling Green", businessState: "KY", businessPostalCode: "42101", businessCountry: null,
            businessPhone: "(270) 746-7898", mobilePhone: null, primaryPhone: null,
            emailAddress: "walt.beasley@ky.gov", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Melissa", middleName: null, lastName: "Evans",
            suffix: null, company: "KYTC District 3", department: null,
            jobTitle: "Project Development Branch Manager", businessStreet1: "900 Morgantown Road",
            businessStreet2: null, businessStreet3: null, businessCity: "Bowling Green", businessState: "KY",
            businessPostalCode: "42101", businessCountry: null, businessPhone: "(270) 746-7898", mobilePhone: null,
            primaryPhone: null, emailAddress: "melissa.evans@ky.gov", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "James", middleName: null, lastName: "Howard",
            suffix: null, company: "KYTC District 4", department: null, jobTitle: null,
            businessStreet1: "634 East Dixie Ave", businessStreet2: null, businessStreet3: null,
            businessCity: "Elizabethtown", businessState: "KY", businessPostalCode: "42701", businessCountry: null,
            businessPhone: "(502) 321-6338", mobilePhone: null, primaryPhone: null,
            emailAddress: "james.howard@ky.gov", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Carla", middleName: null, lastName: "Shelton",
            suffix: null, company: "KYTC District 4", department: null, jobTitle: null,
            businessStreet1: "634 East Dixie Ave", businessStreet2: null, businessStreet3: null,
            businessCity: "Elizabethtown", businessState: "KY", businessPostalCode: "42701", businessCountry: null,
            businessPhone: "(502) 321-6338", mobilePhone: null, primaryPhone: null,
            emailAddress: "carla.shelton@ky.gov", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Matthew", middleName: null, lastName: "Warren",
            suffix: null, company: "KYTC District 4", department: null,
            jobTitle: "Environmental Section Supervisor", businessStreet1: "634 East Dixie Ave",
            businessStreet2: null, businessStreet3: null, businessCity: "Elizabethtown", businessState: "KY",
            businessPostalCode: "42701", businessCountry: null, businessPhone: "(502) 321-6338", mobilePhone: null,
            primaryPhone: null, emailAddress: "matthew.warren@ky.gov", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Trey", middleName: null, lastName: "Pedley",
            suffix: null, company: "KYTC District 4", department: null, jobTitle: null,
            businessStreet1: "634 East Dixie Ave", businessStreet2: null, businessStreet3: null,
            businessCity: "Elizabethtown", businessState: "KY", businessPostalCode: "42701", businessCountry: null,
            businessPhone: "(502) 321-6338", mobilePhone: null, primaryPhone: null,
            emailAddress: "trey.pedley@ky.gov", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Austin", middleName: null, lastName: "McLimore",
            suffix: null, company: "KYTC District 4", department: null, jobTitle: null,
            businessStreet1: "634 East Dixie Ave", businessStreet2: null, businessStreet3: null,
            businessCity: "Elizabethtown", businessState: "KY", businessPostalCode: "42701", businessCountry: null,
            businessPhone: "(502) 321-6338", mobilePhone: null, primaryPhone: null,
            emailAddress: "austin.mclimore@ky.gov", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Eric", middleName: null, lastName: "Houtchen",
            suffix: null, company: "Owensboro Municipal Utilities", department: null, jobTitle: null,
            businessStreet1: "2070 Tamarack Rd", businessStreet2: null, businessStreet3: null,
            businessCity: "Owensboro", businessState: "KY", businessPostalCode: "42301", businessCountry: null,
            businessPhone: "(270) 926-3200", mobilePhone: null, primaryPhone: null,
            emailAddress: "houtchenep@omu.org", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Joe", middleName: null, lastName: "Ranburger",
            suffix: null, company: "Owensboro Municipal Utilities", department: null,
            jobTitle: "Electric Distribution Superintendent", businessStreet1: "2070 Tamarack Rd",
            businessStreet2: null, businessStreet3: null, businessCity: "Owensboro", businessState: "KY",
            businessPostalCode: "42301", businessCountry: null, businessPhone: "(270) 926-3200", mobilePhone: null,
            primaryPhone: null, emailAddress: "ranburgerja@omu.org", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Mark", middleName: null, lastName: "Ballard",
            suffix: null, company: "Owensboro Municipal Utilities", department: null, jobTitle: null,
            businessStreet1: "2070 Tamarack Rd", businessStreet2: null, businessStreet3: null,
            businessCity: "Owensboro", businessState: "KY", businessPostalCode: "42301", businessCountry: null,
            businessPhone: "(270) 926-3200", mobilePhone: null, primaryPhone: null,
            emailAddress: "ballardmp@omu.org", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Dakota", middleName: null, lastName: "Basham",
            suffix: null, company: "Owensboro Municipal Utilities", department: null, jobTitle: null,
            businessStreet1: "2070 Tamarack Rd", businessStreet2: null, businessStreet3: null,
            businessCity: "Owensboro", businessState: "KY", businessPostalCode: "42301", businessCountry: null,
            businessPhone: "(270) 926-3200", mobilePhone: null, primaryPhone: null,
            emailAddress: "bashamda@omu.org", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Mark", middleName: null, lastName: "Rhinerson",
            suffix: null, company: "Owensboro Municipal Utilities", department: null, jobTitle: null,
            businessStreet1: "2070 Tamarack Rd", businessStreet2: null, businessStreet3: null,
            businessCity: "Owensboro", businessState: "KY", businessPostalCode: "42301", businessCountry: null,
            businessPhone: "(270) 926-3200", mobilePhone: null, primaryPhone: null,
            emailAddress: "rhinersonmf@omu.org", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Joe", middleName: null, lastName: "Schepers",
            suffix: null, company: "Owensboro Municipal Utilities", department: null,
            jobTitle: "Electric Distribution Superintendent", businessStreet1: "2070 Tamarack Rd",
            businessStreet2: null, businessStreet3: null, businessCity: "Owensboro", businessState: "KY",
            businessPostalCode: "42301", businessCountry: null, businessPhone: "(270) 926-3200", mobilePhone: null,
            primaryPhone: null, emailAddress: "schepersjs@omu.org", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Derek", middleName: "N.", lastName: "Proffitt",
            suffix: null, company: "Payne & Associates, Inc", department: null, jobTitle: null,
            businessStreet1: "509 Emory Drive", businessStreet2: null, businessStreet3: null,
            businessCity: "Owensboro", businessState: "KY", businessPostalCode: "42301", businessCountry: null,
            businessPhone: "(270) 683-9875", mobilePhone: null, primaryPhone: null,
            emailAddress: "dnpffs@gmail.com", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Chris", middleName: null, lastName: "Stone",
            suffix: null, company: "Payne & Associates, Inc", department: null, jobTitle: null,
            businessStreet1: "509 Emory Drive", businessStreet2: null, businessStreet3: null,
            businessCity: "Owensboro", businessState: "KY", businessPostalCode: "42301", businessCountry: null,
            businessPhone: "(270) 683-9875", mobilePhone: null, primaryPhone: null,
            emailAddress: "chris@payne-associates.com", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Jason", middleName: "M.", lastName: "Hurt",
            suffix: null, company: "Payne & Associates, Inc", department: null, jobTitle: null,
            businessStreet1: "509 Emory Drive", businessStreet2: null, businessStreet3: null,
            businessCity: "Owensboro", businessState: "KY", businessPostalCode: "42301", businessCountry: null,
            businessPhone: "(270) 683-9875", mobilePhone: null, primaryPhone: null,
            emailAddress: "jhurt@payne-associates.com", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Gordon", middleName: null, lastName: "Barnett",
            suffix: null, company: "Pendleton County Water District", department: null, jobTitle: null,
            businessStreet1: "45 Sahara St", businessStreet2: null, businessStreet3: null, businessCity: "Falmouth",
            businessState: "KY", businessPostalCode: "41040", businessCountry: null,
            businessPhone: "(859) 654-6964", mobilePhone: null, primaryPhone: null, emailAddress: "water@fuse.net",
            webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Josh", middleName: null, lastName: "Moore",
            suffix: null, company: "Pendleton County Water District", department: null, jobTitle: null,
            businessStreet1: "45 Sahara St", businessStreet2: null, businessStreet3: null, businessCity: "Falmouth",
            businessState: "KY", businessPostalCode: "41040", businessCountry: null,
            businessPhone: "(859) 654-6964", mobilePhone: null, primaryPhone: null, emailAddress: "water@fuse.net",
            webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Rick", middleName: null, lastName: "Liggett",
            suffix: null, company: "Riverfront Planning & Development", department: null,
            jobTitle: "Director of Planning & Development", businessStreet1: "101 E 4th Street",
            businessStreet2: null, businessStreet3: null, businessCity: "Owensboro", businessState: "KY",
            businessPostalCode: "42303", businessCountry: null, businessPhone: "(270) 687-8350", mobilePhone: null,
            primaryPhone: null, emailAddress: "liggettrf@owensboro.org", webPage: null),
        Contact.Seed(clientId: null, title: null, firstName: "Rita", middleName: null, lastName: "Jacobs",
            suffix: null, company: "Regional Water Resource Agency", department: null, jobTitle: null,
            businessStreet1: "2101 Grimes Ave", businessStreet2: null, businessStreet3: null,
            businessCity: "Owensboro", businessState: "KY", businessPostalCode: "42303", businessCountry: null,
            businessPhone: "(270) 687-8450", mobilePhone: null, primaryPhone: null,
            emailAddress: "rkamjac@yahoo.com", webPage: null)
    ];
}